### ISSUE TITLE
Can we create a dropdown as input source?

### ISSUE THREAD

**Issue by rodrigofaerman** [sawhney17/logseq-smartblocks#14]
was wondering if it is possible to create a dropdown as input source? instead of creating a variable with <%setinput: inputName%>, I would pre-populate a list of values to then selecte one of them.

![Tvs3d5uw](https://user-images.githubusercontent.com/444470/163684708-b412e47b-be36-44dc-a188-85f9910fa0c6.png)

i have a different number of events, for example. i would populate as possible input those 5 options, and then select one.

**Comment by MehsEzeerf** [comment]
This would great!  If I am understanding it correctly.  I was hoping to try an convert a smartblock from roam research over to logseq and this feature request would be superhelpful https://github.com/dvargas92495/SmartBlocks/issues/104

**Comment by piyush-das** [comment]
This would indeed be a great feature. For example say some of my notes have a difficulty property and the only valid options would perhaps be ["Easy", "Medium", "Hard"]. And during taking the input for template rendering perhaps these values can be displayed for the user to pick from. Not only would this lead to better ease of use, but would also ensure that the particular tags always take the right value since selecting from a list of options would make sure there are no Typos.

Hopefully this feature request does get incorporated. Thanks

**Comment by sawhney17** [comment]
This is the feature I’ll be working on next.

Any ideas for the syntax?

<%setInput: event{call, hang up, hello, bye}%>


This would create an event block with 4 options, call, hang up, hello and bye

**Comment by rodrigofaerman** [comment]
I think it's perfect.

would those values be considered as pages, or we can explicitly declare with [[ ]]?

**Comment by sawhney17** [comment]
I'm thinking explicit declaration.  Just like with the current implementation of set input. You can still of course use other commands like current page, NLP etc.

**Comment by pat-githubber** [comment]
Noob here.
Could you provide an example on how to use this syntax in Logseq, please 🙏🏻
 
> <%setInput: event{call, hang up, hello, bye}%>
> 
> This would create an event block with 4 options, call, hang up, hello and bye
> […](#)
