### ISSUE TITLE
Smartblock do not work on 0.8.5

### ISSUE THREAD

**Issue by mzwlevi** [sawhney17/logseq-smartblocks#40]
macOS 12.5.1
smartblocks 3.4.6
This is the video:

https://user-images.githubusercontent.com/78029539/189115034-a065386f-0f78-4b45-b6c5-de417a12ff21.mov

**Comment by BuaaLzd** [comment]
I met the same issue, after updating to 0.8.5.

**Comment by lsharkey** [comment]
Same problem as well.  Creating the button works fine, but then clicking on it does nothing.  I've tried several different buttons, based on several different templates, all of which worked fine before the 0.8.5 update.

+ logseq 0.8.5, installed via FlatPak
+ Pop!_OS 22.04 LTS, kernel v. 5.18.10-76051810-generic, x86_64
+ GNOME v. 42.2
+ X11 Windowing

**Comment by sawhney17** [comment]
Does inserting through command t work?

**Comment by BuaaLzd** [comment]
command+t and /creat inline..., both do not work after updating to 0.8.5, I have to reinstall 0.8.4.

**Comment by sawhney17** [comment]
Should be fixed in 0.8.6

**Comment by mzwlevi** [comment]
> Should be fixed in 0.8.6
> […](#)
> On 9 Sep 2022 at 7:10 AM +0400, BuaaLzd ***@***.***>, wrote: command+t and /creat inline..., both do not work after updating to 0.8.5, I have to reinstall 0.8.4. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Nice

**Comment by lsharkey** [comment]
> Does inserting through command t work?
Hi, no, it doesn't.  This is what happens when I try:

+ `mod+t` (which I changed to `mod+g` to test; I already have `mod+t` in use for something else): nothing happens.
+ `/ Insert Smartblock`: the menu pops up, but then when I click on a template, nothing happens.  I have to use `Esc` to get the menu to close. If instead of clicking on the template name, I type it in to the search box, when I hit `Enter`, nothing happens.
+ For either of the `/ Create Inline Smartblock` commands, the code is added to the screen, and I can fill in the template name, but as soon as I move outside the brackets and hit `Enter`, the code disappears and nothing else happens.
+ For `/ Create SmartBlock Button` everything works as expected to create the button, but then clicking on the button does nothing.

**Comment by BuaaLzd** [comment]
> Yeah. Consistent with the description on GitHub for logseq. Will be fix d next logseq versión.
> […](#)

Report, 0.8.6 is just released, but nothing changed after updating, mod+t or /insert smart..., neither works.

**Comment by sawhney17** [comment]
Interesting. Should've been fixed. Will give it a look.

**Comment by turtletree** [comment]
One more data point

MacOS 12.5
Logseq 0.8.6
Smartblock 3.4.6

`Create Inline *` does nothing
`Create Inline SmartBlock Button` creates the button, clicking the button does nothing
I don't know what `mod + t` does but apparently nothing so far.

I'm a new user to Logseq/Smartblock. I tried to install/uninstall Smartblock a few times, didn't seem to help.

**Comment by BuaaLzd** [comment]
0.8.7 is out, but this plugin seems still not working. help.

**Comment by sawhney17** [comment]
Submitted a bug report to logseq. Looks like the bug that was fixed in the API, while similar, was not identical.

**Comment by sawhney17** [comment]
Should work in the latest version of Smartblocks now.

**Comment by lsharkey** [comment]
It's working!  Thank you!

**Comment by sawhney17** [comment]
This issue has been solved upstream. Will be fixed in the next logseq version.
